/**
 * Hookify Rules for Herald Pattern Learning
 *
 * These rules integrate with Claude Code's hookify plugin to:
 * 1. Remind to check patterns at session start
 * 2. Remind to capture patterns at session end
 */

export const HERALD_HOOKIFY_RULES = {
  // Prompt rule: remind to check patterns on first substantive prompt
  promptCheck: {
    filename: "hookify.herald-patterns-check.local.md",
    content: `---
# Herald Pattern Check - Auto-generated by herald init
# Reminds Claude to check learned patterns at session start
name: herald-patterns-check
enabled: true
event: prompt
action: remind
conditions:
  - field: user_prompt
    operator: regex_match
    pattern: .{20,}
---

**Herald Reminder:** Have you checked \`herald_patterns()\` for learned patterns from past sessions?

Patterns help you avoid past mistakes and apply proven approaches.
`,
  },

  // Session end rule: remind to capture patterns
  sessionEnd: {
    filename: "hookify.herald-capture-reminder.local.md",
    content: `---
# Herald Capture Reminder - Auto-generated by herald init
# Reminds to capture patterns before session ends
name: herald-capture-reminder
enabled: true
event: Stop
action: remind
conditions:
  - field: stop_reason
    operator: exists
---

**Herald Reminder:** Before ending, consider capturing patterns:

- Something worked well? \`herald reflect - that was smooth\`
- Something was frustrating? \`herald reflect - that was rough\`

Captured patterns help future sessions learn from this one.
`,
  },
};

export function getHookifyRulesContent(): Array<{ filename: string; content: string }> {
  return Object.values(HERALD_HOOKIFY_RULES);
}
